version: "3.8"

services:
  #database
  mysql:
    container_name: mysql-database
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "shop"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - shop-db:/var/lib/mysql
volumes:
  shop-db:
